language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

before_install:
    - composer self-update

install:
    - composer install --dev

after_script:
    - travis_retry php vendor/bin/coveralls -v

matrix:
    fast_finish: true
    allow_failures:
      - php: hhvm